include ../Makefile.am

all:
	$(CD) test && make && cd ..
	$(CD) test2 && make && cd ..
	$(CD) system && make && cd ..
	
clean:
	$(CD) test && make clean && cd ..
	$(CD) test2 && make clean && cd ..
	$(CD) system && make clean && cd ..
