include ../../Makefile.am

all:
	cd echo && make && cd ..
	cd cat && make && cd ..
	cd cd && make && cd ..

clean:
	cd echo && make clean && cd ..
	cd cat && make clean && cd ..
	cd cd && make cd && cd ..
